import type { ShoppingListItem, User } from '@ui-kit/components/types';

export const mockUser: User = {
  id: '1',
  name: 'Alice Johnson',
  // avatarUrl: 'https://i.pravatar.cc/150?img=1',
};

export const mockCategories: string[] = ['Produce', 'Bakery', 'Dairy', 'Meat', 'Snacks'];
export const mockUnits: string[] = ['pcs', 'kg', 'g', 'l', 'pack'];

export const mockItems: ShoppingListItem[] = [
  {
    id: '1',
    name: 'Milkkkkkk kkkkkkkkk kkkk and some other stuff',
    quantity: 2000,
    unit: 'L',
    category: 'Dairy',
    isBought: false,
    isCurrent: false,
    isDeleted: false,
    estimatedPrice: 100,
    currency: 'USD',
    addedBy: 'Alice',
    addedAt: new Date(),
    notes: 'This is a note for the item, it can be very long and contain a lot of information',
  },
  {
    id: '2',
    name: 'Bread',
    quantity: 1,
    unit: 'pcs',
    category: 'Bakery',
    isBought: false,
    isCurrent: true,
    isDeleted: false,
    estimatedPrice: 5,
    currency: 'USD',
    addedBy: 'Alice',
    addedAt: new Date(),
  },
  {
    id: '3',
    name: 'Eggs',
    quantity: 12,
    unit: 'pcs',
    category: 'Dairy',
    isBought: true,
    isCurrent: false,
    isDeleted: false,
    estimatedPrice: 10,
    currency: 'USD',
    addedBy: 'Alice',
    addedAt: new Date(),
  },
  {
    id: '4',
    name: 'Chicken',
    quantity: 1,
    unit: 'kg',
    category: 'Meat',
    isBought: false,
    isCurrent: false,
    isDeleted: false,
    estimatedPrice: 10,
    currency: 'USD',
    addedBy: 'Alice',
    addedAt: new Date(),
  },
  {
    id: '5',
    name: 'Beer',
    quantity: 1,
    unit: 'L',
    category: 'Alcohol',
    isBought: true,
    isCurrent: true,
    isDeleted: false,
    estimatedPrice: 10,
    currency: 'USD',
    addedBy: 'Alice',
    addedAt: new Date(),
  },
  {
    id: '6',
    name: 'Beer',
    quantity: 1,
    unit: 'L',
    category: 'Alcohol',
    isBought: false,
    isCurrent: true,
    isDeleted: true,
    estimatedPrice: 10,
    currency: 'USD',
    addedBy: 'Alice',
    addedAt: new Date(),
  },
  {
    id: '7',
    name: 'Other',
    quantity: 1,
    unit: 'L',
    category: '',
    isBought: false,
    isCurrent: false,
    isDeleted: false,
    estimatedPrice: 0,
    currency: 'USD',
    addedBy: 'Alice',
    addedAt: new Date(),
  }
]; 