import type { ListItem } from '@/entities/list/types';
import type { User } from '@/entities/user/types';

export const mockUser: User = {
  id: '1',
  name: 'Alice Johnson',
  // avatarUrl: 'https://i.pravatar.cc/150?img=1',
};

export const mockCategories: string[] = ['Produce', 'Bakery', 'Dairy', 'Meat', 'Snacks', 'Alcohol', 'Frozen', 'Pantry'];
export const mockUnits: string[] = ['pcs', 'kg', 'g', 'l', 'pack', 'box'];

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000);

export const mockItems: ListItem[] = [
  // Within last week
  {
    id: '1',
    name: 'Milk',
    quantity: 2,
    unit: 'l',
    category: 'Dairy',
    isCurrent: false,
    estimatedPrice: 100,
    currency: 'USD',
    addedAt: daysAgo(2),
    notes: 'Bought recently',
    boughtAt: daysAgo(2),
    deletedAt: null,
  },
  {
    id: '2',
    name: 'Bananas',
    quantity: 6,
    unit: 'pcs',
    category: 'Produce',
    isCurrent: false,
    estimatedPrice: 12,
    currency: 'USD',
    addedAt: daysAgo(3),
    notes: '',
    boughtAt: daysAgo(1),
    deletedAt: null,
  },
  {
    id: '3',
    name: 'Frozen Pizza',
    quantity: 2,
    unit: 'box',
    category: 'Frozen',
    isCurrent: true,
    estimatedPrice: 20,
    currency: 'USD',
    addedAt: daysAgo(5),
    notes: 'Try new brand',
    boughtAt: null,
    deletedAt: daysAgo(5),
  },
  // Within last month
  {
    id: '4',
    name: 'Bread',
    quantity: 1,
    unit: 'pcs',
    category: 'Bakery',
    isCurrent: true,
    estimatedPrice: 5,
    currency: 'USD',
    addedAt: daysAgo(15),
    boughtAt: null,
    deletedAt: daysAgo(15),
    notes: '',
  },
  {
    id: '5',
    name: 'Butter',
    quantity: 1,
    unit: 'pack',
    category: 'Dairy',
    isCurrent: false,
    estimatedPrice: 8,
    currency: 'USD',
    addedAt: daysAgo(20),
    notes: 'Salted',
    boughtAt: daysAgo(18),
    deletedAt: null,
  },
  {
    id: '6',
    name: 'Tomatoes',
    quantity: 5,
    unit: 'pcs',
    category: 'Produce',
    isCurrent: false,
    estimatedPrice: 7,
    currency: 'USD',
    addedAt: daysAgo(25),
    notes: 'Overripe',
    boughtAt: null,
    deletedAt: daysAgo(24),
  },
  // Within last 3 months
  {
    id: '7',
    name: 'Eggs',
    quantity: 12,
    unit: 'pcs',
    category: 'Dairy',
    isCurrent: false,
    estimatedPrice: 10,
    currency: 'USD',
    addedAt: daysAgo(50),
    boughtAt: daysAgo(48),
    deletedAt: null,
    notes: '',
  },
  {
    id: '8',
    name: 'Rice',
    quantity: 1,
    unit: 'kg',
    category: 'Pantry',
    isCurrent: false,
    estimatedPrice: 4,
    currency: 'USD',
    addedAt: daysAgo(60),
    notes: '',
    boughtAt: null,
    deletedAt: daysAgo(60),
  },
  {
    id: '9',
    name: 'Orange Juice',
    quantity: 2,
    unit: 'l',
    category: 'Snacks',
    isCurrent: false,
    estimatedPrice: 6,
    currency: 'USD',
    addedAt: daysAgo(80),
    notes: 'For breakfast',
    boughtAt: daysAgo(79),
    deletedAt: null,
  },
  // Within last half year
  {
    id: '10',
    name: 'Chicken',
    quantity: 1,
    unit: 'kg',
    category: 'Meat',
    isCurrent: false,
    estimatedPrice: 10,
    currency: 'USD',
    addedAt: daysAgo(120),
    boughtAt: null,
    deletedAt: daysAgo(120),
    notes: '',
  },
  {
    id: '11',
    name: 'Ice Cream',
    quantity: 1,
    unit: 'box',
    category: 'Frozen',
    isCurrent: false,
    estimatedPrice: 7,
    currency: 'USD',
    addedAt: daysAgo(150),
    notes: 'Chocolate',
    boughtAt: daysAgo(149),
    deletedAt: null,
  },
  {
    id: '12',
    name: 'Potatoes',
    quantity: 10,
    unit: 'kg',
    category: 'Produce',
    isCurrent: false,
    estimatedPrice: 15,
    currency: 'USD',
    addedAt: daysAgo(180),
    notes: 'Sprouted',
    boughtAt: null,
    deletedAt: daysAgo(179),
  },
  // Within last year
  {
    id: '13',
    name: 'Beer',
    quantity: 6,
    unit: 'l',
    category: 'Alcohol',
    isCurrent: true,
    estimatedPrice: 20,
    currency: 'USD',
    addedAt: daysAgo(250),
    boughtAt: daysAgo(249),
    deletedAt: null,
    notes: '',
  },
  {
    id: '14',
    name: 'Cereal',
    quantity: 2,
    unit: 'box',
    category: 'Pantry',
    isCurrent: false,
    estimatedPrice: 8,
    currency: 'USD',
    addedAt: daysAgo(300),
    notes: '',
    boughtAt: null,
    deletedAt: daysAgo(300),
  },
  {
    id: '15',
    name: 'Wine',
    quantity: 1,
    unit: 'l',
    category: 'Alcohol',
    isCurrent: false,
    estimatedPrice: 25,
    currency: 'USD',
    addedAt: daysAgo(320),
    notes: 'Red',
    boughtAt: daysAgo(319),
    deletedAt: null,
  },
  // Over a year ago
  {
    id: '16',
    name: 'Old Cheese',
    quantity: 1,
    unit: 'kg',
    category: 'Dairy',
    isCurrent: false,
    estimatedPrice: 15,
    currency: 'USD',
    addedAt: daysAgo(400),
    boughtAt: null,
    deletedAt: daysAgo(400),
    notes: 'Expired',
  },
  {
    id: '17',
    name: 'Whiskey',
    quantity: 1,
    unit: 'l',
    category: 'Alcohol',
    isCurrent: false,
    estimatedPrice: 50,
    currency: 'USD',
    addedAt: daysAgo(500),
    notes: '',
    boughtAt: null,
    deletedAt: daysAgo(500),
  },
  {
    id: '18',
    name: 'Canned Beans',
    quantity: 4,
    unit: 'pcs',
    category: 'Pantry',
    isCurrent: false,
    estimatedPrice: 6,
    currency: 'USD',
    addedAt: daysAgo(600),
    notes: '',
    boughtAt: daysAgo(599),
    deletedAt: null,
  },
];

