import type { ListItem } from '@/entities/list/types';
import type { User } from '@/entities/user/types';
import type { Category } from '@/shared/types/category';

export const mockUser: User = {
  id: '1',
  name: 'Alice Johnson',
  // avatarUrl: 'https://i.pravatar.cc/150?img=1',
};

export const mockCategoriesWithColors: Category[] = [
  { name: 'Produce', color: 'SAGE' },
  { name: 'Bakery', color: 'MAUVE' },
  { name: 'Dairy', color: 'CREAM' },
  { name: 'Meat', color: 'CORAL' },
  { name: 'Snacks', color: 'SKY' },
  { name: 'Household', color: 'YELLOW' },
];

export const mockItems: ListItem[] = [
  {
    id: '1',
    name: 'Milkkkkkk kkkkkkkkk kkkk and some other stuff',
    quantity: 2000,
    unit: 'l',
    category: 'Dairy',
    isCurrent: false,
    estimatedPrice: 100,
    addedAt: new Date(),
    notes: 'This is a note for the item, it can be very long and contain a lot of information',
    boughtAt: null,
    deletedAt: null,
  },
  {
    id: '2',
    name: 'Bread',
    quantity: 1000,
    unit: 'pcs',
    category: 'Bakery',
    isCurrent: true,
    estimatedPrice: 5,
    addedAt: new Date(),
    boughtAt: null,
    deletedAt: null,
    notes: '',
  },
  {
    id: '3',
    name: 'Eggs',
    quantity: 1200,
    unit: 'pcs',
    category: 'Dairy',
    isCurrent: false,
    estimatedPrice: 10,
    addedAt: new Date(),
    boughtAt: null,
    deletedAt: null,
    notes: '',
  },
  {
    id: '4',
    name: 'Chicken',
    quantity: 1,
    unit: 'kg',
    category: 'Meat',
    isCurrent: false,
    estimatedPrice: 10,
    addedAt: new Date(),
    boughtAt: null,
    deletedAt: null,
    notes: '',
  },
  {
    id: '5',
    name: 'Detergent',
    quantity: 1,
    unit: 'l',
    category: 'Household',
    isCurrent: true,
    estimatedPrice: 10,
    addedAt: new Date(),
    boughtAt: new Date(),
    deletedAt: null,
    notes: '',
  },
  {
    id: '6',
    name: 'Bleach',
    quantity: 1,
    unit: 'l',
    category: 'Household',
    isCurrent: true,
    estimatedPrice: 10,
    addedAt: new Date(),
    boughtAt: null,
    deletedAt: new Date(),
    notes: '',
  },
  {
    id: '7',
    name: 'Other',
    quantity: 1,
    unit: 'l',
    category: '',
    isCurrent: false,
    estimatedPrice: 0,
    addedAt: new Date(),
    boughtAt: null,
    deletedAt: null,
    notes: '',
  },
];
